<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="PRG_Test" Id="{386d7645-b19a-4291-b699-b6f2f3f4c2a7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Test
VAR
	convertFunctionsTest : ConvertFunctionsTest;
	periodicTriggerTest : PeriodicTriggerTest;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>