<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="ReplaceAllAny" Id="{4dfe1242-7df8-0cc0-1e8f-c32f9f237b90}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION ReplaceAllAny
VAR_INPUT
	in : ANY;
	replaced : T_MaxString;
	with : T_MaxString;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ReplaceAllAnyType(in, replaced, with);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>