<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="PRG_Test" Id="{c6742641-04bf-0196-0ddd-a724414d1ebe}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Test
VAR
	convertFunctionsTest : ConvertFunctionsTest;
	periodicTriggerTest : PeriodicTriggerTest;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>