<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="IsLessThanOrEqualAnyType" Id="{2b1c8f92-0781-0e7b-2091-b8bea93306d5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION IsLessThanOrEqualAnyType : BOOL
VAR_INPUT
	a					: __SYSTEM.AnyType; // A and B have to be same type
	b					: __SYSTEM.AnyType; // A and B have to be same type
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[IsLessThanOrEqualAnyType := NOT IsGreaterThanAnyType(a, b);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>