<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="IsNotEqualAnyType" Id="{8f4f1bf4-b286-00c9-33da-ccf45fdc45a9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION IsNotEqualAnyType : BOOL
VAR_INPUT
	a					: __SYSTEM.AnyType; // A and B have to be same type
	b					: __SYSTEM.AnyType; // A and B have to be same type
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[IsNotEqualAnyType := NOT IsEqualAnyType(a, b);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>