<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Swap" Id="{ce22f68c-8e35-0101-0495-56324846ee4d}" SpecialFunc="None">
    <Declaration><![CDATA[// Swaps values of to variables
FUNCTION Swap
VAR_INPUT
	a : ANY;
	b : ANY;
END_VAR
VAR
	temp : POINTER TO BYTE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[temp := __NEW(BYTE, a.diSize);

MEMCPY(temp, a.pValue, a.diSize);
MEMCPY(a.pValue, b.pValue, a.diSize);
MEMCPY(b.pValue, temp, a.diSize);

__DELETE(temp);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>