<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="PRG_Test" Id="{f561285f-0a78-0d21-2985-5942483404f0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Test
VAR
	validateFunctionsTest : ValidateFunctionsTest;
	manipulateFunctionsTest : ManipulateFunctionsTest;
	convertFunctionsTest : ConvertFunctionsTest;
	
	sb255Test : StringBuilder255Test;
	buildStringInlineTest : BuildStringInlineTest;
	sbExtBufferTest : StringBuilderExtBufferTest;
	sbInfiniteTest : StringBuilderInfiniteTest;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>