<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_Test" Id="{68af6fdb-1ffc-4105-a501-ed469ea4d0b7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Test
VAR
	comparisonFunctionsTest : ComparisonFunctionsTest;
	compareAnyTypeTest : CompareAnyTypeTest;
	
	manipulateFunctionsTest : ManipulateFunctionsTest();
	quickSortFunctionsTest : QuickSortFunctionsTest;

	tableSerializerTest : TableSerializerTest;
	tableDeserializerTest : TableDeserializerTest;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>