<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="IsInRangeInclusive2D" Id="{e3369920-1f5c-099b-2b1a-c1f44360d0ba}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION IsInRangeInclusive2D : BOOL
VAR_INPUT
	point : Point2D;
	range : Range2D;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IsInRangeInclusive2D := 
	IsInRangeInclusive(point.X, range.X)
	AND IsInRangeInclusive(point.Y, range.Y)
	;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>