<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="SecondsToTime" Id="{9f0ce1c2-aa18-084e-2cc7-2c5d5d34bc29}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION SecondsToTime : TIME
VAR_INPUT
	seconds : LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SecondsToTime := LREAL_TO_TIME(seconds * 1000);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>