<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="PRG_Test" Id="{1ef4c86c-be7d-46ac-b138-0dab6a048ca7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Test
VAR
	isInRangeFunctionsTest : IsInRangeInclusiveFunctionsTest;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>