<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="PRG_Test" Id="{5869bc1e-7216-0262-2153-7c31dd278f58}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Test
VAR
	isInRangeFunctionsTest : IsInRangeInclusiveFunctionsTest;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>